
# Execute the command to set up the environment
execute_process(
  COMMAND cmake -E env_vs9_wince "STANDARDSDK_500 (ARMV4I)"
  OUTPUT_VARIABLE ENV_OUTPUT
)


set(CMAKE_SYSTEM_VERSION 8.0)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_NAME WindowsCE)
#set(CMAKE_GENERATOR_TOOLSET CE500) # Can be omitted for 8.0
#set(CMAKE_GENERATOR_PLATFORM SDK_AM335X_SK_WEC2013_V310)

SET(CMAKE_C_COMPILER   "C:/VisualStudio9/VC/ce/bin/x86_arm/cl.exe")
SET(CMAKE_CXX_COMPILER  "C:/VisualStudio9/VC/ce/bin/x86_arm/cl.exe" )

SET (CMAKE_C_COMPILER_WORKS 1)
SET (CMAKE_CXX_COMPILER_WORKS 1)


set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set(COMPILE_DEFINITIONS_COMMON "-D_USE_32BIT_TIME_T -D_WIN32_WCE=0x500 -DUNDER_CE -DWINCE -DARM -D_ARM_ -DSTANDARDSHELL_UI_MODEL -DCOLIBRI_CE5 -D_UNICODE -DUNICODE")
set(CMAKE_CXX_FLAGS "${COMPILE_DEFINITIONS_COMMON} /FD /EHsc /MT /fp:fast /Zc:wchar_t- /GR- /W4 /nologo /c /Zi /TP /QRarch5t " CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG "/RTC1 -D_DEBUG " )
set(CMAKE_CXX_FLAGS_RELEASE "/O2 /RTC1 -DNDEBUG" )

