

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(CMAKE_VERBOSE_MAKEFILE TRUE)

string(REGEX REPLACE "/nologo" "" CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT}")

if( "${CMAKE_GENERATOR_PLATFORM}" MATCHES "(x64|WIN64)")
  set(WINFLAGS "-DWIN32 -DWIN64 " )
elseif("${CMAKE_GENERATOR_PLATFORM}" STREQUAL "WIN32")
  set(WINFLAGS "-DWIN32 -D_USE_32BIT_TIME_T" )
else()
endif()

set(COMPILE_DEFINITIONS_COMMON "-DWINVER=0x0500 -D_MBCS -D_WINDOWS -D_CRT_SECURE_NO_DEPRECATE")
set(CMAKE_CXX_FLAGS "${WINFLAGS} ${COMPILE_DEFINITIONS_COMMON}  /Gm /EHsc /Zc:wchar_t- /Od /W3 /c /Zi /TP" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG "/RTC1 -D_DEBUG -D_WINDOWS" )
set(CMAKE_CL_NOLOGO "")


